braindump/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('journal.urls')),
    url(r'^journal/', include('journal.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

journal/urls.py
from django.conf.urls import url
from . import views

app_name = 'journal'

urlpatterns = [
    url(r'^$', views.IndexView, name='index_view'),
    url(r'^add/', views.EntryView, name="entry_view"),
]

journal/models.py
from django.db import models
from datetime import datetime

today = datetime.today().strftime("%Y-%m-%d")

# Create your models here.

class DailyImage(models.Model):
    date = models.DateField(auto_now_add=True, unique=True)
    name = models.CharField(max_length = 1000)
    image = models.CharField(max_length = 1000)
    location = models.CharField(max_length = 1000)

    def __str__(self):
        return str(self.date) + ": " + self.name + ", " + self.location #originally str(self.date)

class JournalEntry(models.Model):
    date = models.DateField(auto_now_add=True)
    today_grateful = models.CharField(max_length = 500)
    affirmations = models.CharField(max_length = 500)
    amazing_things = models.CharField(max_length = 500)
    today_better = models.CharField(max_length = 500)
    wish_change = models.CharField(max_length = 500)
    brain_dump = models.CharField(max_length = 5000)
    image = models.ForeignKey(DailyImage, to_field='date', default=today)

    def __str__(self):
        if len(self.brain_dump) < 100:
            return self.brain_dump
        else:
            return self.brain_dump[0:100] + '  ...'

journal/forms.py
from django.forms import ModelForm, Textarea
from django.utils.translation import ugettext_lazy as _
from .models import *

class JournalEntryForm(ModelForm):
    class Meta:
        model = JournalEntry
        exclude = ['date', 'image']

journal/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.core.urlresolvers import reverse
from .models import *
from .forms import *

today = datetime.today().strftime("%Y-%m-%d")

images = DailyImage.objects.get(date=today)
if images.location:
    name = images.name + ", " + images.location
else:
    name = images.name


# Create your views here.
def IndexView(request):
    journal_entries = JournalEntry.objects.order_by('-pk')
    template = loader.get_template('journal/index.html')
    context = {
        'journal_entries': journal_entries,
        'images': images,
        'name': name,
        'today': today,
    }
    return HttpResponse(template.render(context, request))

def EntryView(request):
    if request.method == 'POST':
        form = JournalEntryForm(request.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('journal:index_view'))
    else:
        form = JournalEntryForm()
    return render(request, 'journal/add_entry.html', {
        'form': form,
        'images': images,
        'today': today,
    })

journal/templates/journal/add_entry.html
{% extends "journal/base.html" %}
{% block title %}Journal Entry{% endblock %}
{% block header %}{{images.image}}{% endblock header %}
{% block photo-meta %}{{name}}{% endblock photo-meta %}
{% block body %}
    <div class="row text-center">

        <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}<br>

            <div class="form-group">
                <h3>{{today}}</h3>
            </div>

            <div class="form-group">
                {% for entry in form %}
                    <div class="row">
                        <div class="text-center entry_label">
                            {{entry.label}}
                        </div>
                        <div class="col-md-0 col-sm-1 col-xs-1">
                        </div>
                        <div class="col-md-12 col-sm-10 col-xs-10">
                            {{entry}}
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div class="form-group">
                <div class="row text-center" style="padding: 10px">
                    <input type="submit" class="btn btn-success" name="submit" value="Submit"/>
                </div>
            </div>

        </form>
</div>
{% endblock %}

journal/templates/journal/base.html
 <!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Journal{% endblock %}</title>
        {% load staticfiles %}
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap/bootstrap.min.css'%}"/>
        <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap/bootstrap-theme.min.css'%}">
        <script type="text/javascript" src="{% static '/js/bootstrap/bootstrap.min.js'%}"></script>
        <link rel="stylesheet" type="text/css" href="{% static '/journal/css/base.css' %}"/>

    </head>

    <body>
        <!--Header Image-->
        <div class="container-fluid image-header" id="header" style="background: url('{% block header %}{% endblock header %}') no-repeat center center; background-size: cover; background-attachment: fixed;">
        </div>
        <div class="container-fluid image-header-quote">
            <div>
                <h1>"This is a famous quote"</h1>
                <h3>Thomas Edison</h3>
                {% block entry-button %}{% endblock entry-button %}
            </div>
            <div class="row photograph-info">
                <p>{% block photo-meta %}{% endblock photo-meta %}</p>
            </div>
        </div>

        <!--Main body-->
            <div class="container col-md-2 col-sm-1">

            </div>
            <div class="container-fluid body col-md-8 col-sm-10">
                <div class="container-fluid">
                    {% block body %}

                    {% endblock %}
                </div>

            </div>

    </body>
</html>

<!-- this is an edit. -->

journal/templates/journal/index.html
{% extends "journal/base.html" %}

{% block header %}{{images.image}}{% endblock header %}
{% block photo-meta %}{{name}}{% endblock photo-meta %}
{% block entry-button %}
    <a href=" {% url 'journal:entry_view' %} " >
        <h2 class="card-title">
            {{today}}<span class="icon-stack">
            <i class="glyphicon glyphicon-plus"></i>
        </h2>

   </span>
    </a>
{% endblock entry-button %}

{% block body %}


        {% for entry in journal_entries %}
        <a href="#">
            <div class="card" style="background:url('{{entry.image.image}}') no-repeat center center; background-size: cover;">
              <div class="card-block">
                <h2 class="card-title">{{entry.date}}</h2>
                <p class="card-text">{{entry}}.</p>
              </div>
            </div>
        </a>

        {% endfor %}

{% endblock %}